////////////////////////////////////////////////////////////////////////////
// top_with_sram.sv — ADDV Lab 2 Part 1 (pipelined MIPS, SRAM memories)
//
// Same processor as top.sv, but imem/dmem are mapped to the OpenRAM
// SRAM_32x64_1rw macro (synthesis only — the SRAM behavioral model is not
// used for functional simulation).
//
// Hierarchy: testbench -> top -> mips -> {controller, datapath} -> imem, dmem
////////////////////////////////////////////////////////////////////////////
module top (
    input clk, reset,
    output [31:0] writedata, dataadr,
    output memwrite
);
    logic [31:0] pc, instr, readdata;

    // instantiate processor and memories
    mips mips (clk, reset, pc, instr, memwrite, dataadr, writedata, readdata);
    imem imem (pc[7:2], instr);
    dmem dmem (clk, memwrite, dataadr, writedata, readdata);
endmodule


//////////////////////////////////////////////////////////////////////
// Single-cycle MIPS Processor Module (pipelined internals)
//////////////////////////////////////////////////////////////////////
module mips (
    input clk, reset,
    output [31:0] pc,
    input [31:0] instr,
    output memwrite,
    output [31:0] aluout, writedata,
    input [31:0] readdata
);
    logic mem2reg, memwriteD, branch, alusrc, regdst, regwrite, jump;
    logic [2:0] alucontrol;
    logic [31:0] instrD;

    controller c(
        .op(instrD[31:26]), .funct(instrD[5:0]),
        .mem2reg(mem2reg), .memwrite(memwriteD), .branch(branch),
        .alusrc(alusrc), .regdst(regdst), .regwrite(regwrite),
        .jump(jump), .alucontrol(alucontrol)
    );

    datapath dp(
        .clk(clk), .reset(reset),
        .branch(branch), .jump(jump),
        .mem2reg(mem2reg), .memwrite(memwriteD), .alusrc(alusrc),
        .regdst(regdst), .regwrite(regwrite), .alucontrol(alucontrol),
        .instrF(instr), .readdata(readdata),
        .pc(pc), .instrD(instrD),
        .aluout(aluout), .writedata(writedata), .memwriteM(memwrite)
    );
endmodule


//////////////////////////////////////////////////////////////////////
// Data Memory Module — uses 32x64 SRAM model generated by OpenRAM
//////////////////////////////////////////////////////////////////////
module dmem (
    input clk, we,
    input [31:0] a, wd,
    output [31:0] rd
);
    logic csb0;          // chip select (active low)
    logic web0;          // write enable (active low)
    logic [5:0] addr0;   // 6-bit word address
    logic [31:0] din0;   // data input
    logic [31:0] dout0;  // data output

    assign csb0 = 1'b0;      // always enabled
    assign web0 = ~we;       // active high to active low
    assign addr0 = a[7:2];   // word-aligned address
    assign din0 = wd;
    assign rd = dout0;

    SRAM_32x64_1rw dmem_ram (
        .clk0(clk),
        .csb0(csb0),
        .web0(web0),
        .addr0(addr0),
        .din0(din0),
        .dout0(dout0)
    );
endmodule


//////////////////////////////////////////////////////////////////////
// Instruction Memory Module — uses 32x64 SRAM model generated by OpenRAM
//////////////////////////////////////////////////////////////////////
module imem (
    input [5:0] a,
    output [31:0] rd
);
    logic clk0;          // clock (read-only: tied off)
    logic csb0;          // chip select (active low)
    logic web0;          // write enable (active low)
    logic [5:0] addr0;   // 6-bit address
    logic [31:0] din0;   // data input
    logic [31:0] dout0;  // data output

    assign clk0 = 1'b0;      // no clock needed for read-only
    assign csb0 = 1'b0;      // always enabled
    assign web0 = 1'b1;      // always read (never write)
    assign addr0 = a;
    assign din0 = 32'b0;
    assign rd = dout0;

    SRAM_32x64_1rw imem_ram (
        .clk0(clk0),
        .csb0(csb0),
        .web0(web0),
        .addr0(addr0),
        .din0(din0),
        .dout0(dout0)
    );
endmodule
